language: python
python:
  - "3.3"
  - "3.4"
install:
  - echo $READTHEDOCS
  - pip install -U setuptools
  - pip install -U pip
  - pip install zc.buildout
  - pip install -e .[dev]
  - buildout
  - export PATH=./bin:$PATH
script:
  - tangled test
  - nosetests
