language: python
python:
  - "3.3"
install:
  - pip install coverage
  - pip install git+git://github.com/TangledWeb/tangled.git#egg=tangled
  - pip install -e .
script:
  - nosetests tangled --with-coverage
